In [2]:
#陣列運算及統計
##亂數搭配陣列的運用
'''以前單純用random module來建立亂數只能建立一個，若是想建立多個亂數則可用numpy module中的numpy.random module來做。
numpy.random.randint(low, high=None, size=None, dtype=int) --> int or ndarray of ints: Return random integers from low (inclusive) to high (exclusive).
為一function，其中參數low和high可為int or array-like of ints；
而size可為int or tuple of ints，代表Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn.'''

import numpy as np
import pandas as pd

display(np.random.randint(1, 11, size = 10))  #輸出結果為ndarray of ints，注意：此方法不包含最大值
scores = np.random.randint(50, 101, size = (50,5))  #50列*5欄
display(scores)  #輸出結果為ndarray of ints
scores_pd = pd.DataFrame(scores, columns = ["國文","英文","數學","地理","歷史"],index = range(1,51))
scores_pd

array([ 1,  1,  1,  5, 10,  9, 10,  5,  1,  1])

array([[ 66, 100,  72,  54,  84],
       [ 78,  62,  97,  52,  59],
       [ 52,  63,  79,  98,  84],
       [ 99,  70,  79,  87,  60],
       [ 84,  59,  84,  61,  81],
       [ 71,  57,  50,  60,  86],
       [ 70,  98,  76,  95,  75],
       [ 50,  77,  76,  62,  55],
       [ 51,  64,  75,  80,  92],
       [ 70,  91,  77,  92,  83],
       [ 68,  69,  97,  90,  83],
       [ 55,  95,  73,  82,  66],
       [ 98,  50,  77,  91,  98],
       [ 88,  93,  72,  77,  60],
       [ 55, 100,  81,  96,  77],
       [ 53,  61,  51,  53,  58],
       [ 54,  93,  51,  90,  50],
       [ 94,  75,  82,  76,  63],
       [ 63,  81,  81,  50,  65],
       [ 74,  52,  62,  57,  69],
       [ 94,  88,  88,  65,  51],
       [ 90,  62,  96,  88,  55],
       [ 53,  75,  76,  81,  54],
       [ 70,  63,  73,  58,  54],
       [ 85,  76,  78,  57,  87],
       [ 70,  68,  83,  73,  64],
       [ 62,  70,  99,  85,  78],
       [ 56,  68,  54,  87,  97],
       [ 61,  98,  87,  92,  60],
       [ 58,  88,  51,  60,  87],
       [ 62,  55,  86,  92,  90],
       [ 84,  93,  51,  96,  90],
       [ 52,  82,  64, 100,  83],
       [ 65,  68,  58,  71,  76],
       [ 92,  65,  85,  82,  97],
       [ 53,  60,  78,  63,  92],
       [100,  83,  72,  72,  80],
       [ 73,  79,  80,  51,  52],
       [ 60,  98,  70,  60,  54],
       [ 88,  97,  80,  77,  84],
       [ 84,  58,  69,  66,  82],
       [ 59,  96,  71,  96,  88],
       [ 53,  74,  71,  97,  51],
       [ 77,  78,  57,  85,  88],
       [ 91,  93,  57,  70,  79],
       [ 69,  53,  91,  88,  55],
       [ 89,  82,  89,  53,  91],
       [ 83,  82,  95,  62,  68],
       [ 65, 100,  53,  81,  57],
       [ 91,  90,  53,  92,  97]])

     國文   英文  數學   地理  歷史
1    66  100  72   54  84
2    78   62  97   52  59
3    52   63  79   98  84
4    99   70  79   87  60
5    84   59  84   61  81
6    71   57  50   60  86
7    70   98  76   95  75
8    50   77  76   62  55
9    51   64  75   80  92
10   70   91  77   92  83
11   68   69  97   90  83
12   55   95  73   82  66
13   98   50  77   91  98
14   88   93  72   77  60
15   55  100  81   96  77
16   53   61  51   53  58
17   54   93  51   90  50
18   94   75  82   76  63
19   63   81  81   50  65
20   74   52  62   57  69
21   94   88  88   65  51
22   90   62  96   88  55
23   53   75  76   81  54
24   70   63  73   58  54
25   85   76  78   57  87
26   70   68  83   73  64
27   62   70  99   85  78
28   56   68  54   87  97
29   61   98  87   92  60
30   58   88  51   60  87
31   62   55  86   92  90
32   84   93  51   96  90
33   52   82  64  100  83
34   65   68  58   71  76
35   92   65  85   82  97
36   53   60  78   63  92
37  100   83  72   72  80
38   73   79  80   51  52
39   60   98  70   60  54
40   88   97  80   77  84
41   84   58  69   66  82
42   59   96  71   96  88
43   53   74  71   97  51
44   77   78  57   85  88
45   91   93  57   70  79
46   69   53  91   88  55
47   89   82  89   53  91
48   83   82  95   62  68
49   65  100  53   81  57
50   91   90  53   92  97

In [3]:
##欄位調整處理
'''index和columns為objects，可透過該物件的property: index.name和columns.name來指定index和columns的名稱。
pandas.Index.name: Return Index or MultiIndex name. 為Index objects底下的一種property；
pandas.Series.name --> label (hashable object): The name of the Series, also the column name if part of a DataFrame.: Return the name of the Series.
注意：此處範例的columns型態為Index。'''

display(scores_pd.index)
display(scores_pd.columns)
scores_pd.index.name = "學號"
scores_pd.columns.name = "科目"
display(scores_pd)

RangeIndex(start=1, stop=51, step=1)

Index(['國文', '英文', '數學', '地理', '歷史'], dtype='object')

科目   國文   英文  數學   地理  歷史
學號
1    66  100  72   54  84
2    78   62  97   52  59
3    52   63  79   98  84
4    99   70  79   87  60
5    84   59  84   61  81
6    71   57  50   60  86
7    70   98  76   95  75
8    50   77  76   62  55
9    51   64  75   80  92
10   70   91  77   92  83
11   68   69  97   90  83
12   55   95  73   82  66
13   98   50  77   91  98
14   88   93  72   77  60
15   55  100  81   96  77
16   53   61  51   53  58
17   54   93  51   90  50
18   94   75  82   76  63
19   63   81  81   50  65
20   74   52  62   57  69
21   94   88  88   65  51
22   90   62  96   88  55
23   53   75  76   81  54
24   70   63  73   58  54
25   85   76  78   57  87
26   70   68  83   73  64
27   62   70  99   85  78
28   56   68  54   87  97
29   61   98  87   92  60
30   58   88  51   60  87
31   62   55  86   92  90
32   84   93  51   96  90
33   52   82  64  100  83
34   65   68  58   71  76
35   92   65  85   82  97
36   53   60  78   63  92
37  100   83  72   72  80
38   73   79  80   51  52
39   60   98  70   60  54
40   88   97  80   77  84
41   84   58  69   66  82
42   59   96  71   96  88
43   53   74  71   97  51
44   77   78  57   85  88
45   91   93  57   70  79
46   69   53  91   88  55
47   89   82  89   53  91
48   83   82  95   62  68
49   65  100  53   81  57
50   91   90  53   92  97

In [4]:
##陣列運算
'''若多個陣列間有相同的索引(如此處的索引皆為學號1~50)則可透過數學運算子做陣列運算。
注意：型態和數量要相符，因此事先可用info此method來查詢資料相關資訊。'''

display(scores_pd.info())
display(scores_pd["國文"][:10])  #scores_pd["國文"]為一Series，然後抓取前10筆資料[:10]
display(scores_pd["數學"][:10])
display(scores_pd["國文"] + scores_pd["英文"] + scores_pd["數學"] + scores_pd["地理"] + scores_pd["歷史"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國文      50 non-null     int64
 1   英文      50 non-null     int64
 2   數學      50 non-null     int64
 3   地理      50 non-null     int64
 4   歷史      50 non-null     int64
dtypes: int64(5)
memory usage: 2.1 KB

None

學號
1     66
2     78
3     52
4     99
5     84
6     71
7     70
8     50
9     51
10    70
Name: 國文, dtype: int64

學號
1     72
2     97
3     79
4     79
5     84
6     50
7     76
8     76
9     75
10    77
Name: 數學, dtype: int64

學號
1     376
2     348
3     376
4     395
5     369
6     324
7     414
8     320
9     362
10    413
11    407
12    371
13    414
14    390
15    409
16    276
17    338
18    390
19    340
20    314
21    386
22    391
23    339
24    318
25    383
26    358
27    394
28    362
29    398
30    344
31    385
32    414
33    381
34    338
35    421
36    346
37    407
38    335
39    342
40    426
41    359
42    410
43    346
44    385
45    390
46    356
47    404
48    390
49    356
50    423
dtype: int64

In [7]:
##陣列的統計
'''可透過DataFrame中的method來做統計，如DataFrame物件名稱.sum()可作加法統計: Return the sum of the values over the requested axis.
可加入參數axis = index(0)/columns(1)來指定要針對index或columns來執行統計，預設為1。'''

scores_pd["總分"] = scores_pd.sum(axis = 1)  #由左而右(針對index逐列)執行統計；新增欄位
scores_pd

科目   國文   英文  數學   地理  歷史     總分
學號
1    66  100  72   54  84  376.0
2    78   62  97   52  59  348.0
3    52   63  79   98  84  376.0
4    99   70  79   87  60  395.0
5    84   59  84   61  81  369.0
6    71   57  50   60  86  324.0
7    70   98  76   95  75  414.0
8    50   77  76   62  55  320.0
9    51   64  75   80  92  362.0
10   70   91  77   92  83  413.0
11   68   69  97   90  83  407.0
12   55   95  73   82  66  371.0
13   98   50  77   91  98  414.0
14   88   93  72   77  60  390.0
15   55  100  81   96  77  409.0
16   53   61  51   53  58  276.0
17   54   93  51   90  50  338.0
18   94   75  82   76  63  390.0
19   63   81  81   50  65  340.0
20   74   52  62   57  69  314.0
21   94   88  88   65  51  386.0
22   90   62  96   88  55  391.0
23   53   75  76   81  54  339.0
24   70   63  73   58  54  318.0
25   85   76  78   57  87  383.0
26   70   68  83   73  64  358.0
27   62   70  99   85  78  394.0
28   56   68  54   87  97  362.0
29   61   98  87   92  60  398.0
30   58   88  51   60  87  344.0
31   62   55  86   92  90  385.0
32   84   93  51   96  90  414.0
33   52   82  64  100  83  381.0
34   65   68  58   71  76  338.0
35   92   65  85   82  97  421.0
36   53   60  78   63  92  346.0
37  100   83  72   72  80  407.0
38   73   79  80   51  52  335.0
39   60   98  70   60  54  342.0
40   88   97  80   77  84  426.0
41   84   58  69   66  82  359.0
42   59   96  71   96  88  410.0
43   53   74  71   97  51  346.0
44   77   78  57   85  88  385.0
45   91   93  57   70  79  390.0
46   69   53  91   88  55  356.0
47   89   82  89   53  91  404.0
48   83   82  95   62  68  390.0
49   65  100  53   81  57  356.0
50   91   90  53   92  97  423.0

In [8]:
##陣列的統計
'''注意：因上面已新增總分欄位，若像上面直接對整個DataFrame進行統計運算，系統會將總分的值也一起加入運算中，
如此數值就會是錯誤的，因此此處的做法為使用subscript[]選取欲做統計之欄位，接著搭配統計method來執行。'''

scores_pd["平均"] = scores_pd[["國文","英文","數學","地理","歷史"]].mean(axis = 1)
scores_pd

科目   國文   英文  數學   地理  歷史     總分    平均
學號
1    66  100  72   54  84  376.0  75.2
2    78   62  97   52  59  348.0  69.6
3    52   63  79   98  84  376.0  75.2
4    99   70  79   87  60  395.0  79.0
5    84   59  84   61  81  369.0  73.8
6    71   57  50   60  86  324.0  64.8
7    70   98  76   95  75  414.0  82.8
8    50   77  76   62  55  320.0  64.0
9    51   64  75   80  92  362.0  72.4
10   70   91  77   92  83  413.0  82.6
11   68   69  97   90  83  407.0  81.4
12   55   95  73   82  66  371.0  74.2
13   98   50  77   91  98  414.0  82.8
14   88   93  72   77  60  390.0  78.0
15   55  100  81   96  77  409.0  81.8
16   53   61  51   53  58  276.0  55.2
17   54   93  51   90  50  338.0  67.6
18   94   75  82   76  63  390.0  78.0
19   63   81  81   50  65  340.0  68.0
20   74   52  62   57  69  314.0  62.8
21   94   88  88   65  51  386.0  77.2
22   90   62  96   88  55  391.0  78.2
23   53   75  76   81  54  339.0  67.8
24   70   63  73   58  54  318.0  63.6
25   85   76  78   57  87  383.0  76.6
26   70   68  83   73  64  358.0  71.6
27   62   70  99   85  78  394.0  78.8
28   56   68  54   87  97  362.0  72.4
29   61   98  87   92  60  398.0  79.6
30   58   88  51   60  87  344.0  68.8
31   62   55  86   92  90  385.0  77.0
32   84   93  51   96  90  414.0  82.8
33   52   82  64  100  83  381.0  76.2
34   65   68  58   71  76  338.0  67.6
35   92   65  85   82  97  421.0  84.2
36   53   60  78   63  92  346.0  69.2
37  100   83  72   72  80  407.0  81.4
38   73   79  80   51  52  335.0  67.0
39   60   98  70   60  54  342.0  68.4
40   88   97  80   77  84  426.0  85.2
41   84   58  69   66  82  359.0  71.8
42   59   96  71   96  88  410.0  82.0
43   53   74  71   97  51  346.0  69.2
44   77   78  57   85  88  385.0  77.0
45   91   93  57   70  79  390.0  78.0
46   69   53  91   88  55  356.0  71.2
47   89   82  89   53  91  404.0  80.8
48   83   82  95   62  68  390.0  78.0
49   65  100  53   81  57  356.0  71.2
50   91   90  53   92  97  423.0  84.6

In [10]:
##資料排名
'''可透過rank此method來做資料排名。
DataFrame物件名稱.rank() --> same type as caller(Return a Series or DataFrame with data ranks as values.): 
Compute numerical data ranks(1 through n) along axis.
By default, equal values are assigned a rank that is the average of the ranks of those values.
可加入參數axis來指定要針對'index'/0或'columns'/1進行排名，預設為0；
加入參數ascending可指定排名為由大至小或由小至大，為bool，預設為True(小至大)，意思為value值小的排名小(靠前)；
加入參數method可指定相同內容值得資料要如何進行排名，可為'average', 'min', 'max', 'first'以及'dense'，預設為'average': 
How to rank the group of records that have the same value (i.e. ties):
"average": average rank of the group         "min": lowest rank in the group
"max": highest rank in the group             "first": ranks assigned in order they appear in the array
"dense": like 'min', but rank always increases by 1 between groups.'''

scores_pd["排名"] = scores_pd["總分"].rank(method = "min", ascending = False)  #value值由大至小排名；相同value取最小的rank值為rank
scores_pd

科目   國文   英文  數學   地理  歷史     總分    平均    排名
學號
1    66  100  72   54  84  376.0  75.2  26.0
2    78   62  97   52  59  348.0  69.6  36.0
3    52   63  79   98  84  376.0  75.2  26.0
4    99   70  79   87  60  395.0  79.0  14.0
5    84   59  84   61  81  369.0  73.8  29.0
6    71   57  50   60  86  324.0  64.8  46.0
7    70   98  76   95  75  414.0  82.8   4.0
8    50   77  76   62  55  320.0  64.0  47.0
9    51   64  75   80  92  362.0  72.4  30.0
10   70   91  77   92  83  413.0  82.6   7.0
11   68   69  97   90  83  407.0  81.4  10.0
12   55   95  73   82  66  371.0  74.2  28.0
13   98   50  77   91  98  414.0  82.8   4.0
14   88   93  72   77  60  390.0  78.0  17.0
15   55  100  81   96  77  409.0  81.8   9.0
16   53   61  51   53  58  276.0  55.2  50.0
17   54   93  51   90  50  338.0  67.6  43.0
18   94   75  82   76  63  390.0  78.0  17.0
19   63   81  81   50  65  340.0  68.0  41.0
20   74   52  62   57  69  314.0  62.8  49.0
21   94   88  88   65  51  386.0  77.2  21.0
22   90   62  96   88  55  391.0  78.2  16.0
23   53   75  76   81  54  339.0  67.8  42.0
24   70   63  73   58  54  318.0  63.6  48.0
25   85   76  78   57  87  383.0  76.6  24.0
26   70   68  83   73  64  358.0  71.6  33.0
27   62   70  99   85  78  394.0  78.8  15.0
28   56   68  54   87  97  362.0  72.4  30.0
29   61   98  87   92  60  398.0  79.6  13.0
30   58   88  51   60  87  344.0  68.8  39.0
31   62   55  86   92  90  385.0  77.0  22.0
32   84   93  51   96  90  414.0  82.8   4.0
33   52   82  64  100  83  381.0  76.2  25.0
34   65   68  58   71  76  338.0  67.6  43.0
35   92   65  85   82  97  421.0  84.2   3.0
36   53   60  78   63  92  346.0  69.2  37.0
37  100   83  72   72  80  407.0  81.4  10.0
38   73   79  80   51  52  335.0  67.0  45.0
39   60   98  70   60  54  342.0  68.4  40.0
40   88   97  80   77  84  426.0  85.2   1.0
41   84   58  69   66  82  359.0  71.8  32.0
42   59   96  71   96  88  410.0  82.0   8.0
43   53   74  71   97  51  346.0  69.2  37.0
44   77   78  57   85  88  385.0  77.0  22.0
45   91   93  57   70  79  390.0  78.0  17.0
46   69   53  91   88  55  356.0  71.2  34.0
47   89   82  89   53  91  404.0  80.8  12.0
48   83   82  95   62  68  390.0  78.0  17.0
49   65  100  53   81  57  356.0  71.2  34.0
50   91   90  53   92  97  423.0  84.6   2.0

In [11]:
##資料排序
scores_pd.sort_values(by = "排名")

科目   國文   英文  數學   地理  歷史     總分    平均    排名
學號
40   88   97  80   77  84  426.0  85.2   1.0
50   91   90  53   92  97  423.0  84.6   2.0
35   92   65  85   82  97  421.0  84.2   3.0
32   84   93  51   96  90  414.0  82.8   4.0
13   98   50  77   91  98  414.0  82.8   4.0
7    70   98  76   95  75  414.0  82.8   4.0
10   70   91  77   92  83  413.0  82.6   7.0
42   59   96  71   96  88  410.0  82.0   8.0
15   55  100  81   96  77  409.0  81.8   9.0
11   68   69  97   90  83  407.0  81.4  10.0
37  100   83  72   72  80  407.0  81.4  10.0
47   89   82  89   53  91  404.0  80.8  12.0
29   61   98  87   92  60  398.0  79.6  13.0
4    99   70  79   87  60  395.0  79.0  14.0
27   62   70  99   85  78  394.0  78.8  15.0
22   90   62  96   88  55  391.0  78.2  16.0
45   91   93  57   70  79  390.0  78.0  17.0
14   88   93  72   77  60  390.0  78.0  17.0
48   83   82  95   62  68  390.0  78.0  17.0
18   94   75  82   76  63  390.0  78.0  17.0
21   94   88  88   65  51  386.0  77.2  21.0
31   62   55  86   92  90  385.0  77.0  22.0
44   77   78  57   85  88  385.0  77.0  22.0
25   85   76  78   57  87  383.0  76.6  24.0
33   52   82  64  100  83  381.0  76.2  25.0
1    66  100  72   54  84  376.0  75.2  26.0
3    52   63  79   98  84  376.0  75.2  26.0
12   55   95  73   82  66  371.0  74.2  28.0
5    84   59  84   61  81  369.0  73.8  29.0
9    51   64  75   80  92  362.0  72.4  30.0
28   56   68  54   87  97  362.0  72.4  30.0
41   84   58  69   66  82  359.0  71.8  32.0
26   70   68  83   73  64  358.0  71.6  33.0
49   65  100  53   81  57  356.0  71.2  34.0
46   69   53  91   88  55  356.0  71.2  34.0
2    78   62  97   52  59  348.0  69.6  36.0
43   53   74  71   97  51  346.0  69.2  37.0
36   53   60  78   63  92  346.0  69.2  37.0
30   58   88  51   60  87  344.0  68.8  39.0
39   60   98  70   60  54  342.0  68.4  40.0
19   63   81  81   50  65  340.0  68.0  41.0
23   53   75  76   81  54  339.0  67.8  42.0
34   65   68  58   71  76  338.0  67.6  43.0
17   54   93  51   90  50  338.0  67.6  43.0
38   73   79  80   51  52  335.0  67.0  45.0
6    71   57  50   60  86  324.0  64.8  46.0
8    50   77  76   62  55  320.0  64.0  47.0
24   70   63  73   58  54  318.0  63.6  48.0
20   74   52  62   57  69  314.0  62.8  49.0
16   53   61  51   53  58  276.0  55.2  50.0

In [48]:
##DataFrame外觀處理
'''可透過DataFrame中的style此property來做DataFrame外觀(顯示)的處理，會傳回Styler object。
DataFrame物件名稱.style: Returns a Styler object. Contains methods for building a styled HTML representation of the DataFrame.
而Styler object中又有許多的property, method及attribute可使用。

如pandas.io.formats.style.Styler.format()，即Styler物件變數名稱.format() --> Styler: Format the text display value of cells.，
可加入參數formatter指定value值要如何顯示(Object to define how values are displayed.)，可為str, callable(如function), dict or None。
This method assigns a formatting function, formatter, to each cell in the DataFrame. If formatter is None, 
then the default formatter is used. If a callable then that function should take a data value as input and 
return a displayable representation, such as a string. If formatter is given as a string this is assumed to be 
a valid Python format specification and is wrapped to a callable as string.format(x). 
If a dict is given, keys should correspond to column names, and values should be string or callable, as above.；
加入參數subset可指定欲做此處理之資料，可為label, array-like, IndexSlice，
subset: A valid 2d input to DataFrame.loc[<subset>], or, in the case of a 1d input or single key, 
to DataFrame.loc[:, <subset>] where the columns are prioritised, to limit data to *before* applying the function.；
加入參數precision可指定小數點位數，注意只能為int。'''

def format60(v:int):
    if v >= 60:
        return "及格"
    else:
        return "不及格"

scores_pd[["國文","英文","數學","地理","歷史"]].style.format(format60)

In [22]:
##DataFrame外觀處理
'''可透過highlight_between此method來用指定的樣式標記特定資料值，會傳回Styler。
Styler物件變數名稱.highlight_between(): Highlight a defined range with a style. 可加入參數subset，用法同上；
參數left代表Left bound for defining the range，可為scalar or datetime-like, or sequence or array-like，預設為None；
參數right代表Right bound for defining the range，可為scalar or datetime-like, or sequence or array-like，預設為None；
參數inclusive代表Identify whether bounds are closed or open，可為both', 'neither', 'left', 'right'，預設為'both'；
參數color可指定標記的底色(background color)，預設為"yelllow"，注意只能為str；
參數props代表CSS properties to use for highlighting，可上網查詢CSS語法，注意只能為str，預設為None，
注意：若用了props此參數，則不能再用color參數了，否則會顯示錯誤。

小技巧：若有.的語法太長，可在.之前或之後加上反斜線\後即可換行，注意：只適用有.的程式段。
小技巧：若想對同一個Styler object進行多種method，可以直接將不同的method串接於前一個method後，
如此便可以不用用多行來處理同一個object了。'''

scores_pd.style\
.highlight_between(subset = ["國文","英文","數學","地理","歷史"],
                   left = 0,
                   right = 59,
                   #color = 'red',
                   props = "color:white;background-color:red")\
.format(subset = ["平均","排名"], precision = 0).to_excel("scores.xlsx")