In [1]:
import numpy as np
import pandas as pd

display(np.random.randint(1,11,size = 10))  #注意：此方法不包含最大值
scores = np.random.randint(50,101,size = (50,5))
scores_pd = pd.DataFrame(scores,columns = ["國文","英文","數學","地理","歷史"],index = range(1,51))
scores_pd

array([ 7,  6,  1,  4,  5,  9,  1, 10,  8,  2])

     國文   英文  數學   地理  歷史
1    95   86  51   95  56
2    71   64  86   62  91
3    98   96  71   70  92
4    87   59  73   51  63
5    78   65  71   60  99
6    85   70  58   70  54
7    91   58  85   68  77
8    57   60  72   94  80
9    54   76  77   74  55
10   59   53  60   66  74
11  100   87  85   83  92
12   87   57  89   93  96
13   70   64  93   85  83
14   85   74  90   84  62
15   80   84  55   85  66
16   62   52  74   87  70
17   73   66  80   57  97
18   87   53  80   71  83
19   72   73  85   88  57
20   52   60  68   64  79
21   94   66  72   98  51
22   65   86  53   63  69
23   52   67  81   78  90
24   52   80  54   74  99
25   51   99  76   83  60
26   84   63  59   66  81
27   56   82  72   59  75
28   50   79  91   53  88
29   87   87  90   72  84
30   66   81  69   87  88
31   60   52  83   64  84
32   93   51  94  100  64
33   65   52  59  100  88
34   50   62  58   62  97
35   64   98  92   91  84
36   71   59  53  100  50
37   62   58  62   57  69
38   51   54  98   86  87
39   98   62  72   90  95
40   78   60  86   88  66
41   66   99  54   85  73
42   60   69  97   70  91
43   65   81  68   99  57
44   75   55  83   53  95
45   60   96  97   57  71
46   67  100  55   59  64
47   79   80  67  100  85
48   95   82  89   72  73
49   74   88  91   54  69
50   79  100  84   88  66

In [9]:
def test1(value):
    print(value)

def test2(value2):
    return 10

scores_pd.apply(test1)
scores_pd.apply(test2)

1      95
2      71
3      98
4      87
5      78
6      85
7      91
8      57
9      54
10     59
11    100
12     87
13     70
14     85
15     80
16     62
17     73
18     87
19     72
20     52
21     94
22     65
23     52
24     52
25     51
26     84
27     56
28     50
29     87
30     66
31     60
32     93
33     65
34     50
35     64
36     71
37     62
38     51
39     98
40     78
41     66
42     60
43     65
44     75
45     60
46     67
47     79
48     95
49     74
50     79
Name: 國文, dtype: int64
1      86
2      64
3      96
4      59
5      65
6      70
7      58
8      60
9      76
10     53
11     87
12     57
13     64
14     74
15     84
16     52
17     66
18     53
19     73
20     60
21     66
22     86
23     67
24     80
25     99
26     63
27     82
28     79
29     87
30     81
31     52
32     51
33     52
34     62
35     98
36     59
37     58
38     54
39     62
40     60
41     99
42     69
43     81
44     55
45     96
46    100
47     80
48     82
49     88
50    100
Name: 英文, dtype: int64
1     51
2     86
3     71
4     73
5     71
6     58
7     85
8     72
9     77
10    60
11    85
12    89
13    93
14    90
15    55
16    74
17    80
18    80
19    85
20    68
21    72
22    53
23    81
24    54
25    76
26    59
27    72
28    91
29    90
30    69
31    83
32    94
33    59
34    58
35    92
36    53
37    62
38    98
39    72
40    86
41    54
42    97
43    68
44    83
45    97
46    55
47    67
48    89
49    91
50    84
Name: 數學, dtype: int64
1      95
2      62
3      70
4      51
5      60
6      70
7      68
8      94
9      74
10     66
11     83
12     93
13     85
14     84
15     85
16     87
17     57
18     71
19     88
20     64
21     98
22     63
23     78
24     74
25     83
26     66
27     59
28     53
29     72
30     87
31     64
32    100
33    100
34     62
35     91
36    100
37     57
38     86
39     90
40     88
41     85
42     70
43     99
44     53
45     57
46     59
47    100
48     72
49     54
50     88
Name: 地理, dtype: int64
1     56
2     91
3     92
4     63
5     99
6     54
7     77
8     80
9     55
10    74
11    92
12    96
13    83
14    62
15    66
16    70
17    97
18    83
19    57
20    79
21    51
22    69
23    90
24    99
25    60
26    81
27    75
28    88
29    84
30    88
31    84
32    64
33    88
34    97
35    84
36    50
37    69
38    87
39    95
40    66
41    73
42    91
43    57
44    95
45    71
46    64
47    85
48    73
49    69
50    66
Name: 歷史, dtype: int64

國文    10
英文    10
數學    10
地理    10
歷史    10
dtype: int64

In [4]:
def callback1(value):
    return pd.Series([value.max(),value.min(),value.median(),value.mean()],index = ["最高分","最低分","中間值","平均值"])

scores_pd.apply(callback1)

         國文     英文     數學     地理     歷史
最高分  100.00  100.0  98.00  100.0  99.00
最低分   50.00   51.0  51.00   51.0  50.00
中間值   71.00   68.0  75.00   74.0  78.00
平均值   72.24   72.1  75.24   76.3  76.78